

export const INCIDENT_DETAILS_REQUEST = "INCIDENT_DETAILS_REQUEST";
export const INCIDENT_DETAILS_SUCCESS = "INCIDENT_DETAILS_SUCCESS";
export const INCIDENT_DETAILS_FAIL = "INCIDENT_DETAILS_FAIL";
export const INCIDENT_DETAILS_RESET = "INCIDENT_DETAILS_RESET";