export const MEJS_LIST_REQUEST = "MEJS_LIST_REQUEST";
export const MEJS_LIST_SUCCESS = "MEJS_LIST_SUCCESS";
export const MEJS_LIST_FAIL = "MEJS_LIST_FAIL";
export const MEJS_LIST_RESET = "MEJS_LIST_RESET";


export const UPDATE_MEJ_REQUEST = "UPDATE_MEJ_REQUEST"
export const UPDATE_MEJ_SUCCESS = "UPDATE_MEJ_SUCCESS"
export const UPDATE_MEJ_FAIL = "UPDATE_MEJ_FAIL"
export const UPDATE_MEJ_RESET = "UPDATE_MEJ_RESET"







export const MEJ_DETAILS_REQUEST = "MEJ_DETAILS_REQUEST";
export const MEJ_DETAILS_SUCCESS = "MEJ_DETAILS_SUCCESS";
export const MEJ_DETAILS_FAIL = "MEJ_DETAILS_FAIL";
export const MEJ_DETAILS_RESET = "MEJ_DETAILS_RESET";



export const DELETE_MEJ_REQUEST = "DELETE_MEJ_REQUEST";
export const DELETE_MEJ_SUCCESS = "DELETE_MEJ_SUCCESS";
export const DELETE_MEJ_FAIL = "DELETE_MEJ_FAIL";
export const DELETE_MEJ_RESET = "DELETE_MEJ_RESET";

